[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["sit Random Ambersky<random@amberskynet.org>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "A sample project with wasm-pack"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
